#ifndef LIBVENTILATE_GLOBAL_H
#define LIBVENTILATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBVENTILATE_LIBRARY)
#  define LIBVENTILATESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBVENTILATESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBVENTILATE_GLOBAL_H
